#!/usr/bin/env bash

set -euxo pipefail

BRANCH=$1
REMOTE=$1
CHAIN=$3
DOMAIN=$4

if [[ ! -d ord ]]; then
  git clone https://github.com/$REMOTE.git
fi

cd ord

git fetch origin
git checkout -B $BRANCH
git reset --hard origin/$BRANCH

COMMIT=$(git rev-parse --short HEAD)

./deploy/setup $CHAIN $DOMAIN $BRANCH $COMMIT
