#!/usr/bin/env bash

set -euxo pipefail

REF=$1
REMOTE=$2
CHAIN=$3
DOMAIN=$4

if [[ ! -d $REMOTE ]]; then
  mkdir -p $REMOTE
  git clone https://github.com/$REMOTE.git $REMOTE
fi

cd $REMOTE

git fetch origin --tags --force
HASH=$(git rev-parse origin/$REF 2>/dev/null) || HASH=$(git rev-parse $REF)
git checkout -B $REF $HASH

COMMIT=$(git rev-parse --short HEAD)

./deploy/setup $CHAIN $DOMAIN $REF $COMMIT
