#!/usr/bin/env bash
set -euxo pipefail

DOMAIN="ordinals-dev.com"

# Current local working state 
BRANCH=$(git rev-parse --abbrev-ref HEAD)
COMMIT=$(git rev-parse --short HEAD)
DIR="ord-${BRANCH}-${COMMIT}"

# Create own directory for every deploy
ssh root@${DOMAIN} "mkdir -p /var/lib/ord/${DIR}"
rsync -avz --exclude-from='.gitignore' --exclude ".git" ./ root@${DOMAIN}:/var/lib/ord/${DIR}

# Clean and prepare
ssh root@${DOMAIN} "echo 'export BRANCH=${BRANCH}' >> ~/.bashrc  \
  && echo 'export COMMIT=${COMMIT}' >> ~/.bashrc \
  && echo 'export DIR=${DIR}' >> ~/.bashrc \
  && rm /var/lib/ord/index.redb"

ssh root@${DOMAIN} "cd /var/lib/ord/${DIR} \
  && /root/.cargo/bin/cargo build --release \
  && cp ./target/release/ord /usr/local/bin/ord \
  && systemctl stop ord-dev \
  && cp /var/lib/ord/${DIR}/deploy/ord-dev.service /etc/systemd/system/ \
  && systemctl daemon-reload \
  && systemctl enable ord-dev \
  && systemctl restart ord-dev"




# mkdir -p /etc/systemd/system/ord-dev.service.d

# cp /etc/systemd/system/{ord,ord-dev}.service.d/override.conf

# source ~/.cargo/env

# cargo build --release

# if [[  -f /usr/local/bin/ord-dev ]]; then
  # mv /usr/local/bin/ord-dev{,.bak}
# fi

# cp target/release/ord /usr/local/bin/ord-dev

# cp deploy/ord-dev.service /etc/systemd/system/
# systemctl daemon-reload
# systemctl restart ord-dev
