#!/usr/bin/env bash
set -euo pipefail
PS1='$ '
source ~/.bashrc

# Stop, save and export state of running instance
systemctl stop ord-dev

cd /var/lib/ord

/usr/local/bin/ord --bitcoin-data-dir /var/lib/bitcoind \
  --data-dir /var/lib/ord \
  index export \
  --tsv inscription_number_to_id-${BRANCH}-${COMMIT}.tsv

mv inscription_number_to_id-${BRANCH}-${COMMIT}.tsv ./${DIR}
mv index.redb ./${DIR}/index-${BRANCH}-${COMMIT}.redb
