#!/usr/bin/env bash

# This script is idempotent.

set -euxo pipefail

CHAIN=$1
RPC_USER=$2
RPC_PASSWORD=$3
FIH=$4
XPRV=$5

touch ~/.hushlogin

apt-get update
apt-get install --yes \
  acl \
  clang \
  curl \
  libsqlite3-dev\
  libssl-dev \
  locales-all \
  pkg-config \
  ufw \
  vim \
  jq

ufw default allow outgoing
ufw default deny incoming

ufw allow 8080
ufw allow http
ufw allow https
ufw allow ssh

case $CHAIN in
  main)
    # COOKIE_FILE_DIR=/var/lib/bitcoind
    ufw allow 8333
    ufw allow 8332
    ;;
  regtest)
    # COOKIE_FILE_DIR=/var/lib/bitcoind/regtest
    ufw allow 18444
    ufw allow 18443
    ;;
  signet)
    # COOKIE_FILE_DIR=/var/lib/bitcoind/signet
    ufw allow 38333
    ufw allow 38332
    ;;
  test)
    # COOKIE_FILE_DIR=/var/lib/bitcoind/testnet3
    ufw allow 18333
    ufw allow 18332
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

mkdir -p \
  /etc/systemd/system/bitcoind.service.d \
  /etc/systemd/system/ord.service.d

printf "[Service]\nEnvironment=CHAIN=%s\nEnvironment=FIH=%s\nEnvironment=RPC_USER=%s\nEnvironment=RPC_PASSWORD=%s\n" $CHAIN $FIH $RPC_USER $RPC_PASSWORD \
  | tee /etc/systemd/system/bitcoind.service.d/override.conf \
  > /etc/systemd/system/ord.service.d/override.conf

sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sshd -t
systemctl restart sshd

ufw --force enable

if ! which bitcoind; then
  ./bin/install-bitcoin-core-linux
fi
bitcoind --version

if [[ ! -e ~/.cargo/env ]]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

source ~/.cargo/env

rustup update stable

cargo build --release
install --backup target/release/ord /usr/local/bin/ord

id --user bitcoin || useradd --system bitcoin
id --user ord || useradd --system ord

cp deploy/bitcoind.service /etc/systemd/system/

mkdir -p /etc/bitcoin
cp deploy/bitcoin.conf /etc/bitcoin/bitcoin.conf

printf "\nrpcuser=%s\nrpcpassword=%s\n" $RPC_USER $RPC_PASSWORD \
  >> /etc/bitcoin/bitcoin.conf

if [[ ! -e ~/.bitcoin/bitcoin.conf ]]; then
  mkdir -p ~/.bitcoin
  ln -s /etc/bitcoin/bitcoin.conf ~/.bitcoin/bitcoin.conf
fi

systemctl daemon-reload
systemctl enable bitcoind
systemctl restart bitcoind

# while [[ ! -f $COOKIE_FILE_DIR/.cookie ]]; do
#   echo "Waiting for bitcoind…"
#   sleep 1
# done

sleep 60

# DECLARE DESCRIPTORS
LAUNCHPAD_FUNDING_DESC="tr($XPRV/86'/1'/0'/0/*)"
LAUNCHPAD_CONTROL_DESC="tr($XPRV/86'/1'/1'/0/*)"

# GET DESCRIPTORS CHECKSUMS
LAUNCHPAD_FUNDING_DESC_CS=$(bitcoin-cli -chain=test getdescriptorinfo $LAUNCHPAD_FUNDING_DESC | jq -r '.checksum')
LAUNCHPAD_CONTROL_DESC_CS=$(bitcoin-cli -chain=test getdescriptorinfo $LAUNCHPAD_CONTROL_DESC | jq -r '.checksum')

# ADD CHECKSUM TO DESCRIPTORS
LAUNCHPAD_FUNDING_DESC=$LAUNCHPAD_FUNDING_DESC#$LAUNCHPAD_FUNDING_DESC_CS
LAUNCHPAD_CONTROL_DESC=$LAUNCHPAD_CONTROL_DESC#$LAUNCHPAD_CONTROL_DESC_CS

# DECLATE WALLET NAMES
LAUNCHPAD_FUNDING_WALLET_1="launchpad-funding-1"
LAUNCHPAD_FUNDING_WALLET_2="launchpad-funding-2"
LAUNCHPAD_FUNDING_WALLET_3="launchpad-funding-3"
LAUNCHPAD_FUNDING_WALLET_4="launchpad-funding-4"
LAUNCHPAD_CONTROL_WALLET_1="launchpad-control-1"
LAUNCHPAD_CONTROL_WALLET_2="launchpad-control-2"

# CREATE WALLETS WITH DECLARED NAMES
bitcoin-cli -chain=$CHAIN createwallet $LAUNCHPAD_FUNDING_WALLET_1 false true "" false true true  
bitcoin-cli -chain=$CHAIN createwallet $LAUNCHPAD_FUNDING_WALLET_2 false true "" false true true
bitcoin-cli -chain=$CHAIN createwallet $LAUNCHPAD_FUNDING_WALLET_3 false true "" false true true
bitcoin-cli -chain=$CHAIN createwallet $LAUNCHPAD_FUNDING_WALLET_4 false true "" false true true
bitcoin-cli -chain=$CHAIN createwallet $LAUNCHPAD_CONTROL_WALLET_1 false true "" false true true
bitcoin-cli -chain=$CHAIN createwallet $LAUNCHPAD_CONTROL_WALLET_2 false true "" false true true

# IMPORT FUNDING DESCRIPTORS TO FUNDING WALLETS
bitcoin-cli -chain=$CHAIN -rpcwallet=$LAUNCHPAD_FUNDING_WALLET_1 importdescriptors "[{ \"desc\": \"$LAUNCHPAD_FUNDING_DESC\", \"timestamp\":\"now\", \"active\": true, \"range\": [0,999999] }]"
bitcoin-cli -chain=$CHAIN -rpcwallet=$LAUNCHPAD_FUNDING_WALLET_2 importdescriptors "[{ \"desc\": \"$LAUNCHPAD_FUNDING_DESC\", \"timestamp\":\"now\", \"active\": true, \"range\": [1000000,1999999] }]"
bitcoin-cli -chain=$CHAIN -rpcwallet=$LAUNCHPAD_FUNDING_WALLET_3 importdescriptors "[{ \"desc\": \"$LAUNCHPAD_FUNDING_DESC\", \"timestamp\":\"now\", \"active\": true, \"range\": [2000000,2999999] }]"
bitcoin-cli -chain=$CHAIN -rpcwallet=$LAUNCHPAD_FUNDING_WALLET_4 importdescriptors "[{ \"desc\": \"$LAUNCHPAD_FUNDING_DESC\", \"timestamp\":\"now\", \"active\": true, \"range\": [3000000,3999999] }]"

# IMPORT CONTOL DESCRIPTORS TO CONTROL WALLETS
bitcoin-cli -chain=$CHAIN -rpcwallet=$LAUNCHPAD_CONTROL_WALLET_1 importdescriptors "[{ \"desc\": \"$LAUNCHPAD_CONTROL_DESC\", \"timestamp\":\"now\", \"active\": true, \"range\": [0,999999] }]"
bitcoin-cli -chain=$CHAIN -rpcwallet=$LAUNCHPAD_CONTROL_WALLET_2 importdescriptors "[{ \"desc\": \"$LAUNCHPAD_CONTROL_DESC\", \"timestamp\":\"now\", \"active\": true, \"range\": [1000000,1999999] }]"

setfacl -m ord:x /var/lib/bitcoind
# setfacl -m ord:x $COOKIE_FILE_DIR
# setfacl -dm ord:r $COOKIE_FILE_DIR
# setfacl -m ord:r $COOKIE_FILE_DIR/.cookie

journalctl --unit ord --vacuum-time 1s

cp deploy/ord.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable ord
systemctl restart ord
